#!/bin/bash

set -x

if [ ! "$ROOT_CHECK" = "0" ]; then
   if [ "$(id -u)" != "0" ]; then
       true "ERROR: This must be run as root (sudo)!${reset}"
       exit 1
   else
       true "INFO: Script running as root."
   fi
fi

apt-get update
apt-get install grml-debootstrap

grml-debootstrap \
   --mirror ftp://ftp.de.debian.org/debian \
   --arch amd64 \
   --filesystem ext4 \
   --force \
   --hostname host \
   --keep_src_list \
   --password changeme \
   --release wheezy \
   --verbose \
   --vmfile \
   --vmsize 100G \
   --config /etc/debootstrap/config \
   --packages /etc/debootstrap/packages \
   --target ./image
